### ISSUE TITLE
Error: Uncaught, unspecified "error" event. ([object Object]) at Stream.emit 

### ISSUE THREAD

**Issue by MarvinSchenkel** [aivis/user-stream#7]
First of all, thanks for your awesome module! I have been using it for a while now, but occasionally my app crashes with the error of 'unspecified error event'. Any idea what's causing this and how to fix this? See the following for a comprehensive error message:

> Error: Uncaught, unspecified "error" event. ([object Object]) at Stream.emit (events.js:144:17) at ClientRequest.<anonymous> (/node_modules/user-stream/lib/user-stream.js:173:16) at emitOne (events.js:77:13) at ClientRequest.emit (events.js:169:7) at TLSSocket.socketErrorListener (_http_client.js:256:9) at emitOne (events.js:77:13) at TLSSocket.emit (events.js:169:7) at connectErrorNT (net.js:996:8) at nextTickCallbackWith2Args (node.js:442:9) at process._tickCallback (node.js:356:17)

Thanks!
Marvin

**Comment by daltonamitchell** [comment]
Have you created an event handler for errors? I added something like this:

``` js
stream.on('error', function(err) {
  console.log(err); 
});
```

Whenever you get a error, this code would log an object like `{ type: 'response', data: { code: 406 } }`. The code corresponds to the list or [error codes](https://dev.twitter.com/streaming/overview/connecting) found [here](https://dev.twitter.com/streaming/overview/connecting) in the docs toward the bottom of the page.

Once you figure out what the issue is, you can replace the log statement with some code that handle the error(s).

**Comment by aivis** [comment]
Thanks @daltonamitchell ! 

@MarvinSchenkel Please be aware that the `stream.on('error'` can emit different types of error objects:
- `stream.emit('error', {type: 'response', data: {code:response.statusCode}});`
- `stream.emit('error', {type: 'request', data: error});`

https://github.com/aivis/user-stream/blob/master/lib/user-stream.js#L86
